# Generated by Django 5.0.1 on 2024-03-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Books_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('download_count', models.IntegerField(blank=True, null=True)),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('media_type', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Books_Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Books_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Books_Book_Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.books_author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.books_book')),
            ],
            options={
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='books_book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='books.Books_Book_Authors', to='books.books_author'),
        ),
        migrations.CreateModel(
            name='Books_Book_Bookshelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_book')),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_bookshelf')),
            ],
            options={
                'unique_together': {('book', 'bookshelf')},
            },
        ),
        migrations.AddField(
            model_name='books_book',
            name='bookshelves',
            field=models.ManyToManyField(related_name='books', through='books.Books_Book_Bookshelves', to='books.books_bookshelf'),
        ),
        migrations.CreateModel(
            name='Books_Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=32)),
                ('url', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='books.books_book')),
            ],
        ),
        migrations.CreateModel(
            name='Books_Book_Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_book')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_language')),
            ],
            options={
                'unique_together': {('book', 'language')},
            },
        ),
        migrations.AddField(
            model_name='books_book',
            name='languages',
            field=models.ManyToManyField(related_name='books', through='books.Books_Book_Languages', to='books.books_language'),
        ),
        migrations.CreateModel(
            name='Books_Book_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_book')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_subject')),
            ],
            options={
                'unique_together': {('book', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='books_book',
            name='subjects',
            field=models.ManyToManyField(related_name='books', through='books.Books_Book_Subjects', to='books.books_subject'),
        ),
    ]
