# Generated by Django 5.0.1 on 2024-03-21 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_author_books_book_books_bookshelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_book_authors',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.books_author'),
        ),
        migrations.AlterField(
            model_name='books_book_authors',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.books_book'),
        ),
    ]
